//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MixMax.Main.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MixMax.Main.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Package&quot;:{&quot;AllPlaylists&quot;:[{&quot;Name&quot;:&quot;Discover&quot;,&quot;TrackListId&quot;:[1,2,3,4,5,6,7,8]},{&quot;Name&quot;:&quot;Oldies&quot;,&quot;TrackListId&quot;:[1,2,9,10]}],&quot;BlackList&quot;:{&quot;Name&quot;:&quot;Blacklist&quot;,&quot;TrackListId&quot;:[8,12,15]}},&quot;Tracks&quot;:[{&quot;Id&quot;:1,&quot;LastUpdateCount&quot;:5,&quot;ThreeMonthCount&quot;:3,&quot;TotalCount&quot;:5,&quot;Artist&quot;:&quot;the a&apos;s&quot;,&quot;Album&quot;:&quot;a&quot;,&quot;Name&quot;:&quot;aa&quot;,&quot;DoesLike&quot;:true,&quot;AddedOn&quot;:&quot;2016-01-01T00:00:00&quot;,&quot;WasEverInAPlaylist&quot;:false,&quot;FilePath&quot;:&quot;C:\\lolz&quot;},{&quot;Id&quot;:1,&quot;LastUpdateCount&quot;:5,&quot;ThreeMonthCount&quot;:3,&quot;TotalCount&quot;:5,&quot;Artist&quot;:&quot;the a&apos;s&quot;,&quot;Album&quot;:&quot;a&quot;,&quot;Name&quot;:&quot;bb&quot;,&quot;DoesLike&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JsonDataProviderTestExpectedResult {
            get {
                return ResourceManager.GetString("JsonDataProviderTestExpectedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Package&quot;:{&quot;AllPlaylists&quot;:[{&quot;Name&quot;:&quot;Discover&quot;,&quot;TrackListId&quot;:[1,2,3,4,5,6,7,8]},{&quot;Name&quot;:&quot;Oldies&quot;,&quot;TrackListId&quot;:[1,2,9,10]}],&quot;BlackList&quot;:{&quot;Name&quot;:&quot;Blacklist&quot;,&quot;TrackListId&quot;:[8,12,15]}},&quot;Tracks&quot;:[{&quot;Id&quot;:1,&quot;LastUpdateCount&quot;:5,&quot;ThreeMonthCount&quot;:3,&quot;TotalCount&quot;:5,&quot;Artist&quot;:&quot;the a&apos;s&quot;,&quot;Album&quot;:&quot;a&quot;,&quot;Name&quot;:&quot;aa&quot;,&quot;DoesLike&quot;:true,&quot;AddedOn&quot;:&quot;2016-01-01T00:00:00&quot;,&quot;WasEverInAPlaylist&quot;:false,&quot;FilePath&quot;:&quot;C:\\lolz&quot;},{&quot;Id&quot;:1,&quot;LastUpdateCount&quot;:5,&quot;ThreeMonthCount&quot;:3,&quot;TotalCount&quot;:5,&quot;Artist&quot;:&quot;the a&apos;s&quot;,&quot;Album&quot;:&quot;a&quot;,&quot;Name&quot;:&quot;bb&quot;,&quot;DoesLike&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
    }
}
